# Generated by Django 5.0.7 on 2024-08-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_change_category', 'Can change category')]},
        ),
    ]
