# Generated by Django 5.0.7 on 2024-08-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('view_mymodel', 'Can view my model'), ('edit_mymodel', 'Can edit my model'), ('delete_mymodel', 'Can delete my model')]},
        ),
    ]
