# Generated by Django 5.0.7 on 2024-08-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default-profile.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
